---
deployment:
  tasks:
    - export NODEVENV=/home/sehigvkd/nodevenv/edoshatch/20
    - export PATH=$NODEVENV/bin:$PATH
    - cd /home/sehigvkd/edoshatch/.next/standalone && npm install --production
